export default {

    products : [{
        _id:1,
        name: "Fancy Saree",
        category: "Sarees",
        image1: '/images/saree1.jpeg',
        image2: '/images/saree11.jpg',
        price: 6000,
        brand: 'Random',
        rating: 4.0,
        numReviews: 10,
        countInStock: 10,
    },
    {
        _id:2,
        name: "Style Saree",
        category: "Sarees",
        image1: '/images/saree2.jpeg',
        image2: '/images/saree21.jpg',
        price: 2000,
        brand: 'Random',
        rating: 4.5,
        numReviews: 100,
        countInStock: 5,
    },
    {
        _id:3,
        name: "Style Saree",
        category: "Sarees",
        image1: '/images/saree3.jpeg',
        image2: '/images/saree31.jpg',
        price: 5000,
        brand: 'Random',
        rating: 4.5,
        numReviews: 15,
        countInStock: 3,
    },
    {
        _id:4,
        name: "Fit Suit",
        category: "Suits",
        image1: '/images/suit1.jpeg',
        image2: '/images/suit11.jpg',
        price: 1500,
        brand: 'Random',
        rating: 4.5,
        numReviews: 15,
        countInStock: 5,
    },
    {
        _id:5,
        name: "Fit Suit",
        category: "Suits",
        image1: '/images/suit2.jpeg',
        image2: '/images/suit21.jpg',
        price: 2500,
        brand: 'Random',
        numReviews: 15,
        countInStock: 5,
    },
    {
        _id:6,
        name: "Suit",
        category: "Suitss",
        image1: '/images/suit3.jpeg',
        image2: '/images/suit31.jpg',
        price: 1500,
        brand: 'Random',
        rating: 4.5,
        numReviews: 15,
        countInStock: 5,
    },
    

],

}