export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const USER_RESET_REQUEST = 'USER_RESET_REQUEST';
export const USER_RESET_SUCCESS = 'USER_RESET_SUCCESS';
export const USER_RESET_FAIL = 'USER_RESET_FAIL';

export const USER_RESET_LINK_REQUEST = 'USER_RESET_LINK_REQUEST';
export const USER_RESET_LINK_SUCCESS = 'USER_RESET_LINK_SUCCESS';
export const USER_RESET_LINK_FAIL = 'USER_RESET_LINK_FAIL';


export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_ADD_TO_CART_REQUEST = 'USER_ADD_TO_CART_REQUEST';
export const USER_ADD_TO_CART_SUCCESS = 'USER_ADD_TO_CART_SUCCESS';
export const USER_ADD_TO_CART_FAIL = 'USER_ADD_TO_CART_FAIL';

export const USER_UPDATE_CART_REQUEST = 'USER_UPDATE_CART_REQUEST';
export const USER_UPDATE_CART_SUCCESS = 'USER_UPDATE_CART_SUCCESS';
export const USER_UPDATE_CART_FAIL = 'USER_UPDATE_CART_FAIL';

export const USER_DELETE_FROM_CART_REQUEST = 'USER_DELETE_FROM_CART_REQUEST';
export const USER_DELETE_FROM_CART_SUCCESS = 'USER_DELETE_FROM_CART_SUCCESS';
export const USER_DELETE_FROM_CART_FAIL = 'USER_DELETE_FROM_CART_FAIL';

export const USER_CARTITEMS_REQUEST = 'USER_CARTITEMS_REQUEST';
export const USER_CARTITEMS_SUCCESS = 'USER_CARTITEMS_SUCCESS';
export const USER_CARTITEMS_FAIL = 'USER_CARTITEMS_FAIL';
export const USER_CART_SAVE_SHIPPING = 'USER_CART_SAVE_SHIPPING';
export const USER_CART_SAVE_PAYMENT = 'USER_CART_SAVE_PAYMENT';

export const USER_LOGOUT = 'USER_LOGOUT';
